# ---
# - name: check CPU Utilization
#   hosts: localhost
#   gather_facts: no

#   tasks:
#     - name: Get CPU Utilization
#       shell: top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{print 100 - $1"%"}'
#       register: cpu_utilization

#     - name: Display CPU Utilization
#       debug:
#         msg: "cpu utilization is {{ cpu_utilization.stdout }}"
---
- name: check cpu utilization
  hosts: localhost
  gather_facts: yes
  vars_files:
    - Vars/global.yml 

  tasks:
    - name: setting up flag
      job_output: ""

    - name: get cpu utilization
      shell: top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{print 100 - $1"%"}'
      register: cpu_utilization


    - name: Print cpu usage current value 1st time
      debug: 
        msg: " Cpu Utilization is {{ cpu_utilization.stdout}}"

###Comparing the cpu with threshhold value
    # - name: comapre cpu utilization against threshold
    #   set_fact: 
    #     job_output: ""

    # - name: wait for 20 second if cpu utilization exceeds threshold
    #   pause:
    #     seconds: 10
    #   when: threshold_exceeded

    # - name: display result
    #   debug:
    #     msg: "CPU Utilization is {{ cpu_utilization.stdout }}. {{ 'Over Threshold' if threshold_exceeded else 'Under Threshold' }}"
