---
- hosts: localhost
  gather_facts: false

  tasks:
   - name: checking with linux command using shell  module
     shell: ls /home/ansible/folder1/
     register: list_op
     delegate_to: 192.168.15.131
   - debug:
       msg: "{{list_op}}"

   - name: transfering file
     copy:
       src: /home/ansible/folder1/test.txt
       dest: /home/ansible/folder2/test.txt
       remote_src: true
     register: transferfile
     delegate_to: 192.168.15.131
   - debug: 
       msg: "msg{{transferfile}}"

   - name: checking the file copied or not
     shell: ls /home/ansible/folder2/
     register: list_op1
     delegate_to: 192.168.15.131  
   - debug:
       msg: "{{list_op1.stdout}}"

   - debug:
       msg: "file sucessfully copied"
     when: list_op1 is defined and list_op1.stdout == test.txt
     
