---
- hosts: localhost
  gather_facts: false
  become: true
  become_method: su
  tasks:
   - name: checking with linux command using shell  module
     shell: ll
     register: list_op
     delegate_to: localhost
   - debug:
       msg: "{{list_op}}"

   - name: transfering file
     copy:
       src: /home/ansible/folder1/test.txt
       dest: /home/ansible/folder2/test.txt
       remote_src: true

     register: transferfile
   - debug: 
       msg: "msg{{transferfile}}"
