---
- hosts: localhost
  gather_facts: false
  become: true
  become_method: su
  tasks:
   - name: transfering file
     copy:
       src: /home/ansible/folder1/test.txt
       dest: /home/ansible/folder2/test.txt
       remote_src: true

     register: transferfile
   - debug: 
       msg: "msg{{transferfile}}"
