---
- hosts: localhost
  gather_facts: false
  become: true

  tasks:
   - name: transfering file
     copy:
       src: /home/ansible/folder1/test.txt
       dest: /home/ansible/folder2/test.txt

     register: transferfile
   - debug: 
       msg: "{{transferfile}}"
