---
- hosts: localhost
  gather_facts: false

  tasks:
    - name: transfering file
      copy:
        src: /path/to/localhost/folder1/test1
        dest: /path/to/localhost/folder2/test1

      register: transferfile
        debug: 
          msg: "{{transferfile}}"
